import BaseLayout from '@/components/layouts/Main/BaseLayout'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  )
}
